### ISSUE TITLE
Gestion de l'administrateur

### ISSUE THREAD

**Issue by tcht-marie** [CTMcorp/front-fil-rouge-trouve-ton-match#1]
- [ ] CTMcorp/back-fil-rouge-trouve-ton-match#8
- [ ] CTMcorp/back-fil-rouge-trouve-ton-match#9
- [ ] CTMcorp/back-fil-rouge-trouve-ton-match#10
- [ ] CTMcorp/back-fil-rouge-trouve-ton-match#11
- [ ] CTMcorp/back-fil-rouge-trouve-ton-match#12
